CREATE TABLE wms.oauth2_authorization (
    id varchar(100) NOT NULL,
    registered_client_id varchar(100) NOT NULL,
    principal_name varchar(200) NOT NULL,
    authorization_grant_type varchar(100) NOT NULL,
    authorized_scopes varchar(1000) NULL,
    "attributes" text NULL,
    state varchar(500) NULL,
    authorization_code_value text NULL,
    authorization_code_issued_at timestamptz NULL,
    authorization_code_expires_at timestamptz NULL,
    authorization_code_metadata text NULL,
    access_token_value text NULL,
    access_token_issued_at timestamptz NULL,
    access_token_expires_at timestamptz NULL,
    access_token_metadata text NULL,
    access_token_type varchar(100) NULL,
    access_token_scopes varchar(1000) NULL,
    oidc_id_token_value text NULL,
    oidc_id_token_issued_at timestamptz NULL,
    oidc_id_token_expires_at timestamptz NULL,
    oidc_id_token_metadata text NULL,
    refresh_token_value text NULL,
    refresh_token_issued_at timestamptz NULL,
    refresh_token_expires_at timestamptz NULL,
    refresh_token_metadata text NULL,
    user_code_value text NULL,
    user_code_issued_at timestamptz NULL,
    user_code_expires_at timestamptz NULL,
    user_code_metadata text NULL,
    device_code_value text NULL,
    device_code_issued_at timestamptz NULL,
    device_code_expires_at timestamptz NULL,
    device_code_metadata text NULL,
    CONSTRAINT oauth2_authorization_pk PRIMARY KEY (id, registered_client_id, principal_name)
);